version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  notebook:
    build: notebook/
    ports:
      - 8888:8888
    volumes:
       - ./database/:/home/jovyan/work/database
       - ./datamining/:/home/jovyan/work/datamining
    environment:
      - GRANT_SUDO=yes
      